# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='\u6ce8\u518c\u7528\u6237')),
                ('password', models.CharField(max_length=50, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u6ce8\u518c\u90ae\u7bb1')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6ce8\u518c\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u6ce8\u518c\u4fe1\u606f',
            },
        ),
    ]
