# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookquery', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='\u6ce8\u518c\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='\u6ce8\u518c\u7528\u6237'),
        ),
    ]
